import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Theme-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import toast ,{Toaster} from 'react-hot-toast'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen w-full`}>
        <ThemeProvider 
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
              <Header/>
              <Toaster
                position="top-center"
                reverseOrder={false}
              />
              <main className="container mx-auto w-full lg:w-[78%] md:w-[90%]">
              {children}
              </main>
              <Footer/>
           
        </ThemeProvider>
        </body>
    </html>
  );
}
